### ISSUE TITLE
Runtime problem with Gambit 4.7.4

### ISSUE THREAD

**Issue by emedernach** [gambit/gambit#108]
I  have  problem  running  a  bunch  of  code
compiled  with  gambit  scheme version  4.7.4
which run fine with version  4.6.9.

This problem tracked  down to macros, here is
a minimal file:

$ cat list.scm

(define-syntax dummy
  (syntax-rules ()
    ((dummy a b ...)
     (time (begin a b ...)))))

;; SRFI 1 iota
(define (iota count)
  (let loop ((i 1) (result '()))
    (if (> i count)
        (reverse result)
        (loop (+ i 1) (cons i result)))))

(dummy (length (iota 1000000)))

With Gambit version 4.6.9

$ gsc -:s -o list.c -c list.scm
$ gsc -:s -o link.c -link list.c
$ gcc -o list list.c link.c -ldl -lm -lgambc -lutil -L${GAMBITDIR}/lib/ 
-I${GAMBITDIR}/include/
$ ./list
(time (length (iota 1000000)))
    80 ms real time
    79 ms cpu time (61 user, 18 system)
    5 collections accounting for 55 ms real time (48 user, 6 system)
    96000000 bytes allocated
    23512 minor faults
    no major faults

With Gambit version 4.7.4

$ gsc -:s -o list.c -c list.scm
$ gsc -:s -o link.c -link list.c
**\* WARNING -- "$sc-put-cte" is not defined,
**\*            referenced in: ("list.c")
**\* WARNING -- "$syntax-dispatch" is not defined,
**\*            referenced in: ("list.c")
**\* WARNING -- "syntax-error" is not defined,
**\*            referenced in: ("list.c")
$ gcc -o list list.c link.c -ldl -lm -lgambc -lutil -L${GAMBITDIR}/lib/ 
-I${GAMBITDIR}/include/
$ ./list
**\* ERROR IN | list| -- Operator is not a PROCEDURE
(#!unbound
 '#(syntax-object dummy ((top) #(ribcage #(dummy) #((top)) #(dummy))))
 '#<procedure #2>
 '_top_)

**Comment by ochi12** [comment]
I'm having the same problem in 4.8.5 syntax-rules only works on 4.6.9 (with the compiler)

**Comment by feeley** [comment]
It seems that this issue is due to commit 0dce1c39c46ca2864b1c40f4dbe0a10c41489840 contributed by Matt Hastie. That commit changed the psyntax expander so that macro definitions in a file caused residual code to be generated that added these macro definitions to the runtime environment of the compiled program (so that code that is passed to eval can use these macros). The issue is that the ```$sc-put-cte``` function that is used to extend the runtime environment is not defined in the basic Gambit runtime system.  It is defined in the file ```lib/syntax-case.scm``` (derived from ```lib/psyntax73.ss```).  So to properly compile a program containing macro definitions and the ```-:s``` compiler flag it is necessary to link with ```syntax-case.scm```.  Note that this file must be compiled without the ```-:s``` flag.  For example:

```
% cp gambit/lib/syntax-case.scm .
% gsc -c syntax-case.scm
% gsc -:s -exe syntax-case.c srfi-13.scm test.scm 
% ./test
```

**Comment by lewisl** [comment]
This problem still exists in 4.9.5.  Getting ```*** ERROR IN benchmark-vector-gambit# -- Operator is not a PROCEDURE
(#!unbound)```.  The recommended solution of compiling syntax-case to c and then compiling the target source file with that did not correct the problem. 

Use of macros (standard-bindings) and (extended-bindings) caused the problem.

**Comment by lewisl** [comment]
My bad: I didn't include srfi-13; I thought it was used by the OP's code. But, I see it is needed.  Now it is called 13.scm.  

But, that results in worse problems:
```
gsc -:s -exe syntax-case.c 13.scm benchmark-vector-gambit.scm
syntax-case.c:
13.scm:
*** ERROR -- Ill-formed special form
(define-library-type
 exception
 id:
 0bf9b656-b071-404a-a514-0fb9d05cf518
 constructor:
 #f
 extender:
 define-library-type-of-exception
 opaque:)
```

So, let's try compiling 13.scm to c first...
So, that's not nice:
```
gsc -c 13.scm         
*** ERROR -- Can't find file "/Users/lewis/Library/CloudStorage/Dropbox/lisp-play/gambit-play/13#.scm"
```

Let's rename it to srfi-13.scm:
```
mv 13.scm srfi-13.scm
gsc -c srfi-13.scm                                                
*** ERROR -- Can't find file "/Users/lewis/Library/CloudStorage/Dropbox/lisp-play/gambit-play/13#.scm"
```

...hmm: there is something special about the srfi's.  (always autocorrects to Sufi's...). Maybe I need to include the reference in the source file as:

OK, seems to run and compile using (import (Sufi 13)) in the source and, naturally, not including in the compile command.  My bad--the OP was using an earlier version and perhaps needed to explicitly compile with the srfi.

Unfortunately, there are other problems preventing my code from actually working when using (standard-bindings) and (extended-bindings). It was suggested to me by a Windows user I'd see gains, but I can't get it to work on Mac with Apple Silicon.  It is still very respectable.

**Comment by feeley** [comment]
Your issue is completely unrelated to the original issue (which was closed 6 years ago!). Please create a new issue in such cases.

I don't understand why you are trying to compile SRFI-13 which is part of the provided modules in recent releases of Gambit. You shouldn't expect to randomly throw pieces of code together and expect things to work. The files `13.scm` and `13#.scm` and `13.sld` are part of the implementation of SRFI-13 and have to be built together.

Your Scheme code has a parenthesis balancing bug... the `declare` form must include the `(standard-bindings)` etc parts.
If you add the `-warnings` option to `gsc` you will see the problem:

```
$ gsc -exe -warnings lewis.scm
*** WARNING -- "extended-bindings" is not defined,
***            referenced in: ("/tmp/lewis.c")
*** WARNING -- "safe" is not defined,
***            referenced in: ("/tmp/lewis.c")
*** WARNING -- "standard-bindings" is not defined,
***            referenced in: ("/tmp/lewis.c")
```

Here is the corrected code, with minor changes to improve performance:

```
;; #!/usr/bin/env gsi-script -:d0

; this version intended to be used with Gambit Scheme
;   not guaranteed to work with other versions of Scheme

(declare
  (block)             ;; these are documented in the Gambit manual section 6.3
  (standard-bindings)
  (extended-bindings)
  (not safe)
)

; sum the vector
(define (f64vector-sum vec)
  (let ((len (f64vector-length vec)))
    (do ((i (fx- len 1) (fx- i 1))
         (sum 0.0 (fl+ sum (f64vector-ref vec i))))
	((fx< i 0) sum))))

(define (f64vec-bench len fval)
  (let ((vec (make-f64vector len fval)))
    (f64vector-sum vec)))

(define (repeat n len fval)
  (do ((i 0 (fx+ i 1)))
    ((fx= i n))
    (f64vec-bench len fval)))


(time (repeat 1000 100000 0.5)) ; do a sum 1000 times
```

**Comment by lewisl** [comment]
Thank you. I got the same error as reported so long ago. Only search result I found. I did see the doc for the 2 macros but didn’t realize I needed to declare a block. I’ll read about blocks.
- Lewis

On Oct 3, 2023, at 2:51 PM, Marc Feeley ***@***.***> wrote:

﻿

Your issue is completely unrelated to the original issue (which was closed 6 years ago!). Please create a new issue in such cases.

I don't understand why you are trying to compile SRFI-13 which is part of the provided modules in recent releases of Gambit. You shouldn't expect to randomly throw pieces of code together and expect things to work. The files 13.scm and 13#.scm and 13.sld are part of the implementation of SRFI-13 and have to be built together.

Your Scheme code has a parenthesis balancing bug... the declare form must include the (standard-bindings) etc parts.
If you add the -warnings option to gsc you will see the problem:

$ gsc -exe -warnings lewis.scm
*** WARNING -- "extended-bindings" is not defined,
***            referenced in: ("/tmp/lewis.c")
*** WARNING -- "safe" is not defined,
***            referenced in: ("/tmp/lewis.c")
*** WARNING -- "standard-bindings" is not defined,
***            referenced in: ("/tmp/lewis.c")


Here is the corrected code, with minor changes to improve performance:

;; #!/usr/bin/env gsi-script -:d0

; this version intended to be used with Gambit Scheme
;   not guaranteed to work with other versions of Scheme

(declare
  (block)             ;; these are documented in the Gambit manual section 6.3
  (standard-bindings)
  (extended-bindings)
  (not safe)
)

; sum the vector
(define (f64vector-sum vec)
  (let ((len (f64vector-length vec)))
    (do ((i (fx- len 1) (fx- i 1))
         (sum 0.0 (fl+ sum (f64vector-ref vec i))))
        ((fx< i 0) sum))))

(define (f64vec-bench len fval)
  (let ((vec (make-f64vector len fval)))
    (f64vector-sum vec)))

(define (repeat n len fval)
  (do ((i 0 (fx+ i 1)))
    ((fx= i n))
    (f64vec-bench len fval)))


(time (repeat 1000 100000 0.5)) ; do a sum 1000 times

**Comment by feeley** [comment]
The `(declare (block))` does not create a block. It tells the compiler it can assume "block compilation" mode (as opposed to "separate compilation" mode). In block compilation mode the compiler can assume that the only assignments to variables defined in this file are found in this file. For example if the code is

```
(declare (block))
(define msg "hello!")
(define (foo) (println msg))
(foo)
```

will be compiled the same as this code :

```
(define msg "hello!")
(define (foo) (println "hello!"))
(println "hello!")
```

This is possible because the declaration allows the compiler to discover that `msg` and `foo` will always have the value that they are given in the `define` forms.

Block compilation mode is particularly interesting when compiling R7RS libraries because R7RS forbids using `set!` on imported variables. With the R5RS standard this restriction does not exist.
