### ISSUE TITLE
compiler warnings for disabled optimization

### ISSUE THREAD

**Issue by vyzo** [gambit/gambit#249]
Presumably there is a good reason for -Wdisabled-optimization, and I am seeing several scheme modules generate this class of warnings:
```
13__0.c: In function ‘___H__20_13____0’:
13__0.c:55411:1: warning: const/copy propagation disabled: 16526 basic blocks and 52457 registers [-Wdisabled-optimization]
 ___END_M_COD
 ^
13__0.c:55411:1: warning: PRE disabled: 16526 basic blocks and 52457 registers [-Wdisabled-optimization]
13__0.c:55411:1: warning: const/copy propagation disabled: 16526 basic blocks and 52457 registers [-Wdisabled-optimization]
13__0.c:55411:1: warning: const/copy propagation disabled: 16239 basic blocks and 52493 registers [-Wdisabled-optimization]
```

Is this a serious issue that should be addressed at source level? 
it's not clear what causes it yet, but it seems to be all over the place (varied scheme files produced the warning)

**Comment by gambiteer** [comment]
Thank you for reporting this; although it is not a bug in Gambit, it is very interesting.

The option ` -Wdisabled-optimization` is mainly useful for gathering information about gcc.  When gcc is passed `-O1`, it sets up certain optimization passes to be run on the functions in a file.

When Gambit is configured with `--enable-single-host` then it compiles all the scheme functions in a file to a single, quite large, C function.  GCC developers often limit the size of functions that certain optimization passes are applied to, either in the belief that such optimization passes would not improve code of this type, or that the compile-time cost of the optimization pass would be too much for the benefit of runtime speedup of the compiled code.

So `-Wdisabled-optimization` reports when some of these optimization passes are disabled.  (I added the code for this warning to gcc.) I say "some" because gcc developers have not added code to activate this warning everywhere that optimization passes are skipped due to large function size.  You've hit the two places in global common subexpression elimination where either PRE or constant/copy propagation is disabled for this reason in the development gcc sources:
```
  if (n_edges_for_fn (cfun) > 20000 + n_basic_blocks_for_fn (cfun) * 4)
    {
      warning (OPT_Wdisabled_optimization,
               "%s: %d basic blocks and %d edges/basic block",
               pass, n_basic_blocks_for_fn (cfun),
               n_edges_for_fn (cfun) / n_basic_blocks_for_fn (cfun));

      return true;
    }
```
This is not the message that you're seeing, so can I ask what version of gcc you're using?

I intend to spend some time in the next few months going through the gcc sources and rationalizing the use of this warning.

**Comment by vyzo** [comment]
It's quite similar, presumably because I am using gcc-4.9.x:
```
$ gcc --version
gcc (Gentoo 4.9.3 p1.5, pie-0.6.4) 4.9.3
```

**Comment by gambiteer** [comment]
I might try to compile your code with the mainline version of gcc.

Is your code available?  Can you tell me how to build it?

Brad

**Comment by vyzo** [comment]
Yes! The warning came from doing a fresh build of Gerbil with head Gambit:
https://github.com/vyzo/gerbil

Clone the repo, cd into src, and ./build.sh. It takes a little while, but there were warnings from several places.

**Comment by gambiteer** [comment]
How did you build gambit?  With --enable-gcc-opts or something?  Because gcse isn't even enabled at -O1.

**Comment by gambiteer** [comment]
OK, with Gambit configured with
```
```
I see these instances of warnings in Gerbil's code:
```
... compile gx-gambc1
../src/gerbil/runtime/gx-gambc1.c: In function '___H__20_gx_2d_gambc1':
../src/gerbil/runtime/gx-gambc1.c:51438:1: warning: const/copy propagation disabled: 18346 basic blocks and 59607 registers; increase --param max-gcse-memory above 136787776 [-Wdisabled-optimization]
 ___END_M_COD
 ^~~~~~~~~~~~
../src/gerbil/runtime/gx-gambc1.c:51438:1: warning: PRE disabled: 18346 basic blocks and 59607 registers; increase --param max-gcse-memory above 136787776 [-Wdisabled-optimization]
../src/gerbil/runtime/gx-gambc1.c:51438:1: warning: const/copy propagation disabled: 18346 basic blocks and 59607 registers; increase --param max-gcse-memory above 136787776 [-Wdisabled-optimization]
../src/gerbil/runtime/gx-gambc1.c:51438:1: warning: const/copy propagation disabled: 18223 basic blocks and 59667 registers; increase --param max-gcse-memory above 136016472 [-Wdisabled-optimization]
```
and
```
... compile srfi/42
42__1.c: In function '___H__20_42____1':
42__1.c:66585:1: warning: const/copy propagation disabled: 25457 basic blocks and 92725 registers; increase --param max-gcse-memory above 295097544 [-Wdisabled-optimization]
 ___END_M_COD
 ^~~~~~~~~~~~
42__1.c:66585:1: warning: PRE disabled: 25457 basic blocks and 92725 registers; increase --param max-gcse-memory above 295097544 [-Wdisabled-optimization]
42__1.c:66585:1: warning: const/copy propagation disabled: 25457 basic blocks and 92725 registers; increase --param max-gcse-memory above 295097544 [-Wdisabled-optimization]
42__1.c:66585:1: warning: const/copy propagation disabled: 25330 basic blocks and 92725 registers; increase --param max-gcse-memory above 293625360 [-Wdisabled-optimization]
```
This is after configuring Gambit with
```
./configure 'CC=/usr/local/gcc-7.1.0/bin/gcc -march=native -D___CAN_IMPORT_CLIB_DYNAMICALLY' '--enable-single-host' '--enable-multiple-versions' '--enable-shared' '--enable-gcc-opts' '--enable-c-opt=-O2'
```
So it's using the just-released gcc-7.1.0 with the enhanced error message I added to gcc in November, 2015:
```
https://gcc.gnu.org/ml/gcc-patches/2015-11/msg01563.html
```
Increasing the default value of `max-gcse-memory` to 128MB allowed Gambit itself to be built with -O2 without `-Wdisabled-optimization` triggering any warnings.

But your files are a bit bigger.  So if you want these optimizations to be applied, you'll need to add something like `--param max-gcse-memory=300000000` if you want to allocate 300MB of temporary memory to run gcse (global common subexpression elimination) on these files.

**Comment by gambiteer** [comment]
That should be: Gambit was configured with
```
./configure 'CC=/usr/local/gcc-7.1.0/bin/gcc -march=native -D___CAN_IMPORT_CLIB_DYNAMICALLY' '--enable-single-host' '--enable-multiple-versions' '--enable-shared' '--enable-gcc-opts' '--enable-c-opt=-O2'
```

**Comment by vyzo** [comment]
Thanks Brad!

For reference, my Gambit is configured with ` --enable-single-host --enable-c-opt --enable-gcc-opts --enable-multiple-versions --enable-shared --enable-openssl`

**Comment by vyzo** [comment]
I have fixed the issues by setting max-gcse-memory as appropriate:
https://github.com/vyzo/gerbil/commit/51190b8e6f76961b1a5c177e7941dbff79e27bcb

Closing the issue as the main problem has been resolved.
