### ISSUE TITLE
`___glo_list_search_obj' always iterates through all ___glo_struct

### ISSUE THREAD

**Issue by thewhimer** [gambit/gambit#301]
without returning early when found.

**Comment by feeley** [comment]
This is expected.   ```___glo_list_search_obj``` is used to search the global variables to assign a name to globally bound procedures.  This is used by ```write``` to print the name of procedures.  So a ```(write car)``` will display ```#<procedure #2 car>``` not because that procedure contains the name ```car``` but because the global variable ```car``` contains that procedure.  This correctly handles the case ```(let ((temp car)) (set! car cdr) (set! cdr temp) (write car))``` which displays ```#<procedure #2 car>```... in other words it is the environment that assigns names to values.

The Gambit linker constructs an ordered list of all the global variables, and global variables defined by the runtime library, like ```car```, come before those defined in the main program by the programmer.  Moreover, the library's global variables are alphabetically sorted, so ```car``` comes before ```cdr``` and, more importantly ```current-input-port``` comes before ```##current-input-port```. ```___glo_list_search_obj``` finds the *first* global variable in this ordered list that contains the procedure to be printed.  So ```(define aaa car)(write aaa)``` will write ```#<procedure #2 car>``` rather than ```#<procedure #2 aaa>```... then name ```car``` is more telling to the programmer than ```aaa``` even though both variables contain the car procedure.  This has the nice side-effect that ```(write ##current-input-port)``` will write ```#<procedure #2 current-input-port>``` even though both the variable ```current-input-port``` and the variable```##current-input-port``` contain the current-input-port procedure (a parameter object).

A complication arises with the parallel garbage collector.  For performance reasons the "list of global variables" can't be a linear list because this would mean that it must be traversed in a sequential manner (by a single thread) by the garbage collector, and this would hinder parallelism (there are close to 5000 global variables in the runtime library).  So instead the "list of global variables" is actually implemented by multiple sublists of global variables, typically 256 sublists.  When multiple processors are used, say N processors, they each traverse 256/N sublists, in parallel.  In other words the task of traversing the global variables is evenly distributed to all the processors.  The first sublist contains variables at index 0, 256, 512, 768, 1024, etc.  The second sublist contains the variables at index 1, 257, 513, 769, 1025, etc.

This complicates ```___glo_list_search_obj``` because finding the searched procedure in a global variable in one sublist at a certain "depth" in that sublist, doesn't stop the search because the searched procedure might also be found at a lesser depth in another sublist (and thus have a smaller index).

Note that not all global variables are visited.  If the final index of the global variable is i, then the global variable is at a depth of i/256 in sublist i%256. So sublist i%256+1 and above are traversed completely, but sublists i%256 and below are only searched to a depth of i/256 (or less if the procedure is found in another variable).  Probabilistically, 3/4 of the global variables are searched compared to 1/2 of the global variables if a linear list of global variables was used.

**Comment by thewhimer** [comment]
A really thorough explanation, thanks Marc!!

It came to me that there might be multiple global variables linked to the searched value, but not that even then a specific one was need. And that explains `glo_depth' too, and I though it was redundant.

Would be great if a short version of this come with the code. I'm reading Gambit implementation internals, and learned a lot. Thanks again for such a high quality and wonderful implementation for scheme!
