### ISSUE TITLE
Still vectors take half the memory of movable (heap) vectors?

### ISSUE THREAD

**Issue by russpowers** [gambit/gambit#311]
Hi, I was testing out the memory usage of Gambit, and it seemed a bit high, given that I thought each field in a record (or element in a vector) would be of word size.  After looking into it further, it seems like vectors with length less than 255 have an element size of 16 bytes (on x64), while larger vectors will have element size 8 bytes.  I looked through mem.c and _kernel.scm, and 255 words (`___MSECTION_BIGGEST`) seems to be the cutoff for doing a bump allocation on the heap vs a call to `___alloc_scmobj`.

I thought maybe it was just that the gc statistics were being misreported, but `top` confirms that the resident set is double with 254 vs 255 element vectors.  And it doesn't seem to matter what's in the vectors, empty ones give the same result.

Below is some code to demonstrate the issue, it creates a vector of `vec-count` vectors of `elem-count` elements.  Please excuse any weird idioms, I'm still getting the hang of scheme! :grin:

```scheme
(define (build-vector n proc)
  (let ((vec (make-vector n)))
    (do ((i 0 (+ i 1)))
      ((eqv? i n) vec)
      (vector-set! vec i (proc i)))))

(define (vector-test vec-count elem-count fill)
  (let ((vec (build-vector vec-count
                           (lambda (n) (make-vector elem-count fill))))
        (total-elems (+ vec-count (* vec-count elem-count))))
    (##gc)
    (let* ((stats (##process-statistics))
           (live (##f64vector-ref stats 17)))
      (write vec-count)
      (display " vectors of ")
      (write elem-count)
      (display " elements, bytes/element = ")
      (write (/ live total-elems))
      (newline))
    vec))

(vector-test 1000000 254 1.54321)
(vector-test 1000000 255 1.54321)
```
Also, I'm using the master branch of Gambit and gcc 7.2.0 with options `--enable-single-host --enable-c-opt --enable-gcc-opts` on Ubuntu x64.

**Comment by feeley** [comment]
Gambit is being as honest as possible concerning the memory usage.  Small objects are managed with a Cheney-style copying collector with bump allocation, while "large" objects are managed with a mark-sweep non-copying collector and the space for the object is obtained with a call to malloc.  The copying collector uses 2 "spaces" a fromspace and a tospace.  When the GC is running the live objects are copied from the fromspace into the tospace.  When the GC is not running, allocation continues in the tospace and the fromspace is not touched.  At the next GC the roles of the spaces are reversed.

So how can the memory usage of a small object be properly accounted for? You could count the words in the tospace (1 word for the header plus 1 word per field), but then what about the space occupied by the fromspace? It shouldn't be ignored because it is needed for proper operation of the GC and it has an impact on the memory footprint of the process. So Gambit takes the point of view than when N words are allocated for an object in the tospace, there are also N words that are "reserved" for that object in the fromspace so that it can be copied there. There is thus a factor of 2 "bloat" for small objects that reflects how many words in memory are reserved for them, even though most of the time (outside a GC) only half of these words actually contain useful bits of data.

**Comment by russpowers** [comment]
Ohh I see, that makes sense.  I read that Gambit had a copying collector and figured it was some kind of mark and sweep with defragmentation, this is the first time I've heard of Cheney's algorithm.  It seems like a very elegant solution, albeit at the cost of some extra memory.  I recently implemented Immix for a toy language of mine, which worked fairly well.  It's much more complex to maintain than a copying collector, though, and I'm not sure what the effect would be on overall speed.  Anyways, I'm closing the issue, thanks for the explanation!
