### ISSUE TITLE
Build instructions under Windows are either incomplete or incorrect

### ISSUE THREAD

**Issue by lucaregini** [gambit/gambit#379]
I have tried to perform a full bootstrap build under Windows and haven't been able to make it work.

Have tried both using MSYS2 and MSYS 1.0 ( this last using the gcc that comes with mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0).

The configure flag used are:
./configure --enable-single-host --enable-debug --enable-debug-log --enable-debug-c-backtrace --enable-debug-ctrl-flow-history --enable-debug-host-changes --enable-debug-alloc-mem --enable-debug-garbage-collect --enable-rtlib-debug-location --enable-rtlib-debug-source --enable-rtlib-debug-environments --enable-track-scheme --enable-thread-system=win32 --enable-multiple-threaded-vms --enable-smp

The  make bootstrap; make bootclean steps work but the final make step hangs.
As a matter of fact it seems that the generated gsc-boot application buily in the bootstrap step hangs forever and the build remains stuck at the first file _io.scm.

Under a standard linux build the _io.scm file is compiled in a matter of a few seconds.

I have also tried to replace gsc-boot with the gsc that comes from the windows binary distribution and the results are the same.

**Comment by feeley** [comment]
The performance of the system is affected by the level of debugging support selected by the configure options.  Some of the debugging options are very fine grained and log information to a file (gambit.log).  This performance slowdown is moreover amplified by the use of SMP because all processors will be logging to the same file (and this also makes the information hard to read).

The option --enable-debug-host-changes is *extremely* expensive because it logs every transfer of control between functions that go through the trampoline.  It exists for debugging hard to debug situations where it is important to know what were the last few function calls that led to a bug.  So this is kind of a “last hope” when other debugging techniques have failed to solve a bug.  The (newer) option --enable-debug-ctrl-flow-history was created to give approximately the same information when the program crashes, but it logs the information in memory and only dumps it to gambit.log when the program crashes, so it is much more efficient.

The option --enable-debug-garbage-collect will slow down the GC depending on the debugging level runtime option.  When a debugging level >= 1 is used, for example -:d2, the GC will perform checks that detect when the heap is in an inconsistent state (due to a bug in the GC or the rest of the system).

The other debugging options are much less expensive.

As an example, on my machine after a “make bootstrap”, a “make bootclean;make” takes about 4 minutes when only the --enable-single-host option is used and about 16 minutes when all debugging options except --enable-debug-host-changes are used.  With --enable-debug-host-changes it would probably take a few days or maybe weeks…

**Comment by feeley** [comment]
Please try the latest build batch file misc/vstudio.bat to build Gambit with the Visual Studio development environment.
