### ISSUE TITLE
master branch parse cc-options wrong

### ISSUE THREAD

**Issue by jxy** [gambit/gambit#427]
```
$ gsc -cc-options '-march=native -O3' test.scm
cc1: error: bad value ('native -O3') for '-march=' switch
```

Similar errors happen with ld-options.

By the way, GAMBCOMP_VERBOSE does not do anything for me.

**Comment by feeley** [comment]
These options have changed recently (as recently as the latest commit).  This was motivated in part by the need to put any characters in the option, including doublequotes, backslashes, etc.  Now you need one `-cc-options` per C compiler option:

```
% gsc -cc-options '-march=native' -cc-options '-O3' -cc-options '-DMSG="hello world"' test.scm
```

Moreover, to get a verbose output you need to set `GAMBUILD_VERBOSE` (because the script that is invoked is now called `gambuild-C`) or pass the option `-verbose` to gsc.

**Comment by feeley** [comment]
By the way, now you can put the cc-options, ld-options, etc as meta-information in the Scheme source file itself, i.e. in test.scm:

```
(##meta-info cc-options "-march-native" "-O3" "-DMSG=\"hello world\"")
...
```

**Comment by lassik** [comment]
Is there an up-to-date list of all environment variables used by Gambit somewhere?

**Comment by vyzo** [comment]
This is a breaking change. 
Why not introduce `-cc-option` for a single option, and maintain the old behaviour for `-cc-options`?

**Comment by lassik** [comment]
Indeed the name `options` becomes slightly misleading.

**Comment by lassik** [comment]
Then again having both `option` and `options` feels a bit cluttered and is potentially confusing.

Maybe add `option`, keep `options` with the old semantics for now and gradually phase out `options` (deprecation warning)?

**Comment by feeley** [comment]
Unfortunately the old `-cc-options` did not have a clean semantics because it did not really pass the options as-is to the C compiler:

```
% gsc -cc-options '-DFOO="hello"' opts.scm
% gsc -cc-options '-DFOO="hello world"' opts.scm
gcc-8: error: world": No such file or directory
*** ERROR IN ##main -- target compilation or link failed while compiling "opts.scm"
```

This prevents using paths with spaces (which are hard to avoid on Windows due to the essential "C:\Program Files" directory).  For example, you can't do `-cc-options '-IC:\Program Files\foo\include'`.

So breaking compatibility with an unclean semantics is justified.

I could lessen the blow by doing a preprocessing of the cc-options and ld-options to separate options at spaces, unless within double quotes, with the goal that it would mostly work like before in the common case.  However, I'm not sure how to handle `-cc-options '-IC:\Program Files\foo\include'`...

If a preprocessing is added, it might be a good time to add a way to reference build-time environment variables in the options.  Currently (and before) nothings special is done:

```
% gsc -cc-options '-DFOO="path:$PATH"' opts.scm
% gsi opts.o1
path:$PATH
% cat opts.scm
(c-declare #<<EOF

void run() {
  printf("%s\n", FOO);
}

EOF
)

(define run (c-lambda () void "run"))

(run)
```

**Comment by lassik** [comment]
> So breaking compatibility with an unclean semantics is justified.

Agreed. I didn't know about that.

How much dependency do you estimate there is on the old `-cc-options` (plural)? If it had gotchas, could it simply be removed and `-cc-option` (singular) added?

Expanding environment variables may be a good idea, though the precise syntax is worth thinking about. Unix Shell can do both `$FOO` and `${FOO}`; the latter is less ambiguous.

**Comment by feeley** [comment]
I agree that `-cc-options` is currently misleading and should become `-cc-option` unless some preprocessing that splits at spaces is added.  But this has to be carefully thought through because it would be bad to change this again in a future release.  The good news is that the new handling of `-cc-options` hasn't been in a release yet...

For the environment variable expansion, note that I'm talking about "build-time" expansion.  It is currently possible to do "Scheme compile-time" expansion like this:

```
% gsc -cc-options -DFOO=\"path:$PATH\" opts.scm
```

which works as long as PATH does not contain double quotes, spaces, etc

Build time expansion would allow variables in cc-options within Scheme files:

```
(##meta-info cc-options "-DFOO=\"path:$PATH\"") ;; exact variable syntax to be determined
```

So the binding of the environment variables will be the binding when the .c file is compiled.

**Comment by lassik** [comment]
The semantics of the `$` expansion will be a lot easier to understand if only `-cc-option` (singular)  is supported and not `-cc-options`. If we only have the singular version, it's obvious that it will always expand to exactly one command line argument. With the plural one, how will it expand an envar whose value contains spaces and other special characters?

**Comment by vyzo** [comment]
From a software engineering perspective, there is no reason to break all users of ffi and dependent software just like that.
Supporting both `-cc-options` (with (maybe) preprocessing and splitting) and `-cc-option` for a single option are probably the best way forward.

**Comment by jxy** [comment]
> % gsc -cc-options '-DFOO="hello world"' opts.scm
> gcc-8: error: world": No such file or directory

Is this because the string is explicitly split by white space by the scheme program?  I would think if you pass it to shell as is, it would be fine.

**Comment by feeley** [comment]
There is no way for gsc to know that you have used single-quote quotations on the gsc command line:

```
% gsc -cc-options '-DFOO="hello_world"' -e '(pp (caddr (command-line)))'
"-DFOO=\"hello_world\""
% gsc -cc-options -DFOO=\"hello_world\" -e '(pp (caddr (command-line)))'
"-DFOO=\"hello_world\""
% gsc -cc-options '-O3 -g' -e '(pp (caddr (command-line)))'
"-O3 -g"
% gsc -cc-options "-O3 -g" -e '(pp (caddr (command-line)))'
"-O3 -g"
% gsc -cc-options -O3' '-g -e '(pp (caddr (command-line)))'
"-O3 -g"
% gsc -cc-options "-DFOO=' '" -e '(pp (caddr (command-line)))'
"-DFOO=' '"
% gsc -cc-options '-DFOO=" "' -e '(pp (caddr (command-line)))'
"-DFOO=\" \""
```

So gsc doesn't know which quotes to use at the lowest level.

**Comment by feeley** [comment]
> Is there an up-to-date list of all environment variables used by Gambit somewhere?

They are in the Gambit manual, but there are few... just `GAMBOPT` and `GAMBUILD_VERBOSE` are documented.  The script `bin/gambuild-C` (which is called by gsc) takes its parameters through environment variables and some of the settings determined by the configure script.  The environment variables are:

```
when using gsc -obj:
BUILD_OBJ_META_INFO_FILE_PARAM
BUILD_OBJ_CC_OPTIONS_PARAM
BUILD_OBJ_PKG_CONFIG_PARAM
BUILD_OBJ_PKG_CONFIG_PATH_PARAM
BUILD_OBJ_INPUT_FILENAMES_PARAM
BUILD_OBJ_OUTPUT_FILENAME_PARAM

when using gsc -dynamic (the default):
BUILD_DYN_META_INFO_FILE_PARAM
BUILD_DYN_CC_OPTIONS_PARAM
BUILD_DYN_LD_OPTIONS_PRELUDE_PARAM
BUILD_DYN_LD_OPTIONS_PARAM
BUILD_DYN_PKG_CONFIG_PARAM
BUILD_DYN_PKG_CONFIG_PATH_PARAM
BUILD_DYN_INPUT_FILENAMES_PARAM
BUILD_DYN_OUTPUT_FILENAME_PARAM

when using gsc -exe:
BUILD_EXE_META_INFO_FILE_PARAM
BUILD_EXE_CC_OPTIONS_PARAM
BUILD_EXE_LD_OPTIONS_PRELUDE_PARAM
BUILD_EXE_LD_OPTIONS_PARAM
BUILD_EXE_PKG_CONFIG_PARAM
BUILD_EXE_PKG_CONFIG_PATH_PARAM
BUILD_EXE_INPUT_FILENAMES_PARAM
BUILD_EXE_OUTPUT_FILENAME_PARAM
```

**Comment by jxy** [comment]
As far as these examples concerned, gsc treats the string passed in exactly as any build system would do with environment variables, CFLAGS, LDFLAGS, and etc.  It looks like perfectly valid behavior.

Since the string is passed to a shell script anyway, gsc can give the user the responsibility of quoting them properly.  Usual build system just take these flags verbatim, and users expect these to be parsed (shell expansions: brace expansion, tilde expansion, parameter, variable and arithmetic expansion and command substitution, word splitting, and pathname expansion) one more time.

Just like ssh don't quote strings for users, but it rely on the users to quote them.

```
% ssh remote echo "quote'em \"one-more-time\""
mksh: no closing quote
% ssh office-tun echo $(printf "%q" "quote'em \"one-more-time\"")
quote'em "one-more-time"
```

**Comment by feeley** [comment]
That may be the most common practical option (no pun intended) but I have to think about it.  It is just sad to perpetuate "escape hell" that was avoided by the new cc-options semantics.  On the other hand, if I'm not mistaken, it would allow using environment variables in the cc-options easily, for example:

```
% hostname
neo
% ssh arctic "echo running on \$(hostname) with PATH=\\\"\${PATH}\\\""
running on arctic with PATH="/usr/local/bin:/usr/bin:/bin:/usr/games"
```

**Comment by lassik** [comment]
> It is just sad to perpetuate "escape hell" that was avoided by the new cc-options semantics.

👍 

> On the other hand, if I'm not mistaken, it would allow using environment variables in the cc-options easily

Unix and Windows shells have different syntax for string quoting, variable references and other things. Can we guarantee that the options are always evaluated by a Posix shell?

**Comment by feeley** [comment]
> > It is just sad to perpetuate "escape hell" that was avoided by the new cc-options semantics.
> 
> 👍
> 
> > On the other hand, if I'm not mistaken, it would allow using environment variables in the cc-options easily
> 
> Unix and Windows shells have different syntax for string quoting, variable references and other things. Can we guarantee that the options are always evaluated by a Posix shell?

I'm hesitant to force a Posix shell on Windows developers. Gambit has always aimed to satisfy the various "native OS" ways of doing things (in particular filesystem path syntax).

Forcing a Posix shell on Windows would also require a posix shell to be installed by the programmer, because that's not a standard thing.  The Windows cmd.exe can be relied on.

So it feels wrong to only provide the syntax of a Posix shell, and particularly considering the low-level nature of the cc/ld-options which are normally C compiler specific too. On Windows I suspect a typical programmer will expect the Windows "feel" including the paths with backslashes, the Windows semicolon separated %PATH%, and the %FOO% environment variables.

Note that the difference can be hidden behind an OS guard:

```
(##meta-info cc-options (when unix "-DFOO=$FOO"))
(##meta-info cc-options (when windows "-DFOO=%FOO%"))
```

So perhaps that is good enough.  One case where it would be good to have a single notation for environment variables is to access contextual information, like the directory containing the C source file:

```
(##meta-info cc-options "-I${DIRECTORY_OF_C_SOURCE_FILE}/../include")
```

It may become tedious to always duplicate such declarations, although in this particular case it might be necessary to do so because of the difference in path syntax (on the other hand typical dev tools on Windows support the Unix style paths...).

**Comment by lassik** [comment]
> I'm hesitant to force a Posix shell on Windows developers. Gambit has always aimed to satisfy the various "native OS" ways of doing things (in particular filesystem path syntax).
> 
> Forcing a Posix shell on Windows would also require a posix shell to be installed by the programmer, because that's not a standard thing. The Windows cmd.exe can be relied on.

Also 👍 

I wonder if it's safe to replace `/` with `\` in the general case. On the other hand, lots of Windows programs can be given pathnames using Unix-style `/` slashes and they work anyway. I suspect the translation of `/` to `\` is even baked into the Windows API. In that case, it may be that no substitution ever needs to be done by Gambit.

The `$VARIABLE` vs `${VARIABLE}` (POSIX shell) vs `%VARIABLE%` (Windows `.bat` file) syntax is more tricky. We could pick one of them. We could also support all of them, but that makes processing more complex.

**Comment by jxy** [comment]
Either the string
```
-cc-options '-march=native' -cc-options '-O3
```
is parsed by the shell that launches gsc, or the string
```
-cc-options '-march=native -O3'
```
is parsed by the shell that gsc launches.

Quoting strings for the shell by shell utilities would always look messy.  Giving the complexity and responsibility to the users is more sensible and cleaner.

On the other hand, if we want compatibility beyond POSIX, perhaps taking shell out of the equation would be much more sensible.  Perhaps all the `bin/gambuild-X` should be in scheme and use `execve` (or its relatives) to launch C compilers and etc.

**Comment by lassik** [comment]
Scheme and shell have quite similar syntax for double-quoted strings. So whether you do `gsc -cc-option '..."` or `(##meta-info cc-options "...")` you can use double-quotes around the option, and backslashes to escape any special characters. It's nice that the syntax can be the same in both cases as a side-effect of how Scheme, shell and Gambit are designed with no effort from anyone's part.

I and others have suggested doing the build scripts in Scheme, but @feeley would like to keep things so that Gambit programs compiled into C can be shipped standalone, i.e. no Scheme interpreter is needed to finish compiling the program to an OS executable at another compiter.

**Comment by lassik** [comment]
Not relying on POSIX shells makes it possible to use Windows .bat files. Also, most POSIX-compliant shells don't have all the same features; it'd be up to the user to take care of POSIX conformance.

All in all it would be more complex than using execve() and a simple, hand-rolled variable substitution syntax. Shell syntax has many features that are likely to be used unintentionally and have no real purpose in a command line argument. Things like pipelines, subshells, redirects, etc.

**Comment by lassik** [comment]
Though if you parse those options and emit them into a .sh file, you have to quote them with backslashes anyway, so my argument is not as strong.

**Comment by vyzo** [comment]
Any updates on this issue?

As things stand I can't build gerbil without changing the build system to split `-cc-options`, and I don't want to break master for v4.9.3 release.
Is there a good discriminant (perhaps some new bound procedure or other feature) I can use as a feature test to do the right thing automatically?

**Comment by vyzo** [comment]
Another way in which this breaks: consider a gcc option like `--param max-gcse-memory=300000000`.
Previously that worked with `-cc-options` as is; now it will have to be `-cc-options --param -cc-options max-gcse-memory=300000000`; ugly as hell.

**Comment by feeley** [comment]
I'll be working on this in a few days when I get the time.  The old syntax (with multiple C compiler options per --cc-options) will work, and environment variables will be available too.

**Comment by feeley** [comment]
I have changed gambuild-C to support the old syntax and allow access to  environment variables.  See PR #437.  Please try it out and give some feedback.

**Comment by vyzo** [comment]
I have successfully built gerbil with it seems to work fine.

**Comment by jxy** [comment]
Looks good with limited testing.  Allow me to close this issue.
