### ISSUE TITLE
Wrong number of arguments error in gsc `guard`

### ISSUE THREAD

**Issue by lassik** [gambit/gambit#486]
The following works in the interpreter:

```scheme
(guard (_ (else 42))
  (directory-files "nonexistent"))
```

But a compiled executable produces the error:

```
*** ERROR -- Wrong number of arguments passed to procedure
(##with-exception-catcher '#<procedure #2>)
```

Compiler command lines:

* `gsc -exe guardtest.scm `
* `gsc -:r7rs -exe guardtest.scm `

**Comment by rgherdt** [comment]
I took a look at gambit's source code and found two 'guard' related predicates: `**r7rs-guard-expr?` and `**guard-expr?`. Since both use the same identifier `guard`, the first called gets precedence (in this case `**guard-expr?`). By swapping the order they are called in the procedure pt (file _ptree1.scm line 969) the problem is gone. What is the non-R7RS guard?

**Comment by feeley** [comment]
I am currently looking into a solution.  There are two issues.  The first is an incomplete implementation of the R7RS `guard` form in the compiler... apparently the code is incomplete and I can't explain why it is like this.  The fix is not too hard and I have something working locally.

The second issue is at the semantic level.  The R7RS has defined a set of exception handling primitives `with-exception-handler`, `raise`, and `raise-continuable` that have a different behaviour than the similar procedures `with-exception-handler`, `abort`, and `raise` defined by Gambit.  The R7RS exception model requires that the current exception handler at the moment of the call to `with-exception-handler` be remembered by the exception mechanism so that when an exception is raised this exception handler can be reinstated for the execution of the handler.  This is an unfortunate choice that prevents some features of Gambit from working (specifically being able to redefine the actions of primitive operations when they receive arguments of the incorrect type, for example to transparently access remote objects as though they were in the local heap).
