### ISSUE TITLE
Add configure check for clang/LLVM gcc wrapper

### ISSUE THREAD

**Issue by lassik** [gambit/gambit#573]
Ref #568 

Could we use autoconf to detect whether the `gcc` compiler is in fact a wrapper for LLVM's `clang`? The default `gcc` command is such a wrapper is on MacOS and possibly other operating systems.

**Comment by lassik** [comment]
`gcc --version 2>/dev/null | head -n 1 | grep LLVM` can detect the LLVM gcc. The `head -n 1` is not strictly necessary. The `2>/dev/null` prevents part of LLVM's version output from spilling over into the build log...

In C, both GNU GCC and LLVM define `__GNUC__`.  To detect LLVM, `#ifdef __clang__`.

**Comment by feeley** [comment]
When running `./configure CC=gcc` on macOS (using the fake `gcc`) the configure script outputs at the very end:

```
**************************************************************************
***                                                                    ***
*** The clang compiler is being used.  Please be aware that the build  ***
*** may take a very long time (over 30 minutes on a fairly fast        ***
*** machine with clang 3.0).  Configuring with GNU GCC will give a     ***
*** faster build (1 min on the same machine with GNU GCC 4.2.1) and    ***
*** the executable will be faster.                                     ***
***                                                                    ***
**************************************************************************
```

**Comment by lassik** [comment]
Ah, forgot all about that!

https://github.com/gambit/gambit/blob/b9360cb871a524e575ef75947757df3157894db4/configure.ac#L1258

**Comment by feeley** [comment]
There's an amusing twist to this.  When building the Gambit installer for macOS the configure script invocation is `./configure ... CC=gcc` with a shell script called `gcc` that is used that actually calls the GNU gcc.  This trick is used so that when Gambit is installed by an end-user the `gsc` compiler will work even if only Xcode is installed (with the fake gcc), but `gsi` and `gsc` will actually be executable programs built with GNU gcc (so they are 2x faster than if built with the fake gcc).  Unfortunately, programs compiled by `gsc` in this scenario won't be as fast as a custom build with `./configure ... CC=gcc-9`.  But I think that people using the installer are probably novice users (students, etc) for which the simplicity of saying "just install Xcode" is a bonus.

**Comment by lassik** [comment]
There are also various C innovations like stack and heap guards... I hope the Homebrew people will keep offering a build of GNU GCC that generates code compatible with Apple's LLVM.

**Comment by feeley** [comment]
From experience the two can be mixed, but we'll have to see where Apple is going with clang.

**Comment by lassik** [comment]
True. One never knows about Apple...
