### ISSUE TITLE
Possible enhancements to ci.yml

### ISSUE THREAD

**Issue by eine** [gambit/gambit#590]
@daviwil, you might want to consider some of the following enhancements to `.github/workflows/ci.yml`:

- Instead of `git fetch --prune --unshallow`, use actions/checkout@v2's option `fetch-depth: 0`. You might need to use `git config --global core.autocrlf input`, as commented in https://github.com/eine/setup-msys2#usage. See actions/checkout#250 and actions/checkout#226.

- Use `defaults: run: shell` as explained in https://github.com/eine/setup-msys2#usage, to avoid writting `run: msys2 whatever` multiple times.

- Do you really need `path-type: inherit`? That might produce conflicts if `git`, `make` or some other tools are available in the PATH.

**Comment by daviwil** [comment]
@eine Thanks for the tips!  I do want to switch over to using `msys2` as the shell.  I didn't know about the `default` setting, that's helpful!

For `fetch-depth: 0`, Gambit's `makefile` relies on having Git tags available for part of the build so I had to go a different route to ensure that the tags were getting fetched correctly.  In the past I wasn't able to use `fetch-depth: 0` because it didn't pull tags, but I see now that they added it thanks to the issue you linked: https://github.com/actions/checkout/issues/250#issuecomment-634799150.

Regarding `path-type: inherit`, I think I ran into issues if I didn't use that back when I was using `numworks/setup-msys2` but I'll try removing it now just in case it isn't needed any longer.

**Comment by eine** [comment]
> @eine Thanks for the tips! I do want to switch over to using `msys2` as the shell. I didn't know about the `default` setting, that's helpful!

In fact, I found about it just a few days ago 😆 

> For `fetch-depth: 0`, Gambit's `makefile` relies on having Git tags available for part of the build so I had to go a different route to ensure that the tags were getting fetched correctly. In the past I wasn't able to use `fetch-depth: 0` because it didn't pull tags, but I see now that they added it thanks to the issue you linked: [actions/checkout#250 (comment)](https://github.com/actions/checkout/issues/250#issuecomment-634799150).

I was using `unshallow` for the same reason and I changed it precisely when it was fixed in the issue I linked.

> Regarding `path-type: inherit`, I think I ran into issues if I didn't use that back when I was using `numworks/setup-msys2` but I'll try removing it now just in case it isn't needed any longer.

I see that you are using it for MINGW and for MVSC. That might be the source of the issue: for MVSC I'd expect you to need tools from the host. However, for MINGW all the compilers and libs should be available within the environment.

**Comment by daviwil** [comment]
Thanks again for the pointers @eine!  Looks like PR #591 got merged so you can probably close this now (unfortunately I don't have the ability to do so!).
