### ISSUE TITLE
char-ready? on current-input-port

### ISSUE THREAD

**Issue by jcubic** [gambit/gambit#657]
Just found this inconsistency:

```scheme
(char-ready? (current-input-port))
```
in Gauche and Guile it return `#f` which is correct, but in Kawa and Gambit it return `#t` even that it will hang because it will need to wait for user input. This was reported to Kawa as well [kashell/Kawa#89](https://gitlab.com/kashell/Kawa/-/issues/89).

**Comment by feeley** [comment]
It is not an error.  If you do this at the REPL there is a newline at the end of your expression that is still there and can be read without blocking.  If you get rid of this newline with a call to `read-char` then you get what you expect:

```
> (read-char) ;; this will return #\space (the character just before the comment)
#\space
> (read-char)
#\newline
> (char-ready?)
#t
> (begin (read-char) (char-ready?))
#f
```

In the last expression the newline character at the end of the line is removed by the call to `read-char` so the call to `char-ready?` returns `#f` because there are now no characters that can be read without blocking.
