### ISSUE TITLE
Invoking eval with with-exception-handler freezes the interpreter

### ISSUE THREAD

**Issue by jcubic** [gambit/gambit#658]
I'm trying to write REPL that will work in every Scheme implementation that I have installed on my system.

But I'm not able to invoke eval and display error message in Gamibt it freezes like run in input accepting loop.
```scheme

(import (scheme base)
        (scheme r5rs))

(cond-expand
  (lips)
  (kawa)
  (gambit)
  (guile
   (import (rnrs base)
           (rnrs exceptions)
           (rnrs conditions))
   (define (error-object-message cond)
     (condition-message cond))
   (define (flush-output-port) void))
  (gauche))

(define void (if #f #f))

(define (evaluate expr env)
  (call-with-current-continuation
   (lambda (exit)
     (with-exception-handler
      (lambda (e)
        (exit (error-object-message e)))
      (lambda ()
        (eval expr env))))))

(display (evaluate 'xxx (interaction-environment)))
(newline)
```

I've asked on StackOverflow [How to show error message from eval in Scheme?](https://stackoverflow.com/q/65667115/387194)

Importing base and r5rs solve the issue in Gauche.

**Comment by feeley** [comment]
The reason you get an infinite loop is that the variable `xxx` is unbound so the exception handler `(lambda (e) (exit (error-object-message e)))` is called with an `unbound-global-exception` object and this causes `error-object-message` to be called but the parameter is not an `error-object` (which is specific to the exceptions raised by a call to `error`) so this raises a `type-exception` that causes the same exception handler to be called, and so on forever.

If you want an exception handling that "pops" the current exception handler, use `with-exception-catcher` instead of `with-exception-handler`.  This will avoid the infinite loop.

Converting an exception object to a string can be done this way:

```
(define (exception->string exc)
  (with-output-to-string
    (lambda ()
      (display-exception exc))))
```

It works for `error-object`s and other kinds of exceptions, and also any non-exception object.

**Comment by feeley** [comment]
Below is your code that I have cleaned-up to account for exceptions not being instances of `error-object`:

```
(import (scheme base)
        (scheme r5rs))

(cond-expand
  ((or lips kawa gauche)
   (define (exception->string exc)
     (error-object-message exc)))
  (gambit
   (define (exception->string exc)
     (with-output-to-string
       (lambda ()
         (display-exception exc)))))
  (guile
   (import (rnrs base)
           (rnrs exceptions)
           (rnrs conditions))
   (define (exception->string exc)
     (condition-message exc))))

(define (evaluate expr env)
  (call-with-current-continuation
   (lambda (exit)
     (with-exception-handler
      (lambda (e)
        (exit (exception->string e)))
      (lambda ()
        (eval expr env))))))

(display (evaluate 'xxx (interaction-environment)))
(newline)
```

**Comment by jcubic** [comment]
Thanks, is it possible to convert exception to string without newline at the end, or do you need to use substring to remove newline?

**Comment by feeley** [comment]
The message generated by `display-exception` may be multiple lines, so the newlines are important.  If you want to remove the very last one then use `string-shrink!`:

```
> (define s (string-append "hello\n" "world\n"))
> (string-shrink! s (- (string-length s) 1))
> s
"hello\nworld"
```
