### ISSUE TITLE
Weird Behavior with 24-bit Color Escape Codes

### ISSUE THREAD

**Issue by c0nn3r** [gambit/gambit#661]
I was messing around with `gsi` and I came across some behavior I cannot figure out.

```
> (display "\033[38;5;24mhello\n")
hello (<- gets colored correctly)
> (display "\033[38;2;255;0;0mHello\n")
Hello (<- doesn't get colored correctly)
```

The behavior is the same if I use `gsc` to compile the file. I have verified that on other Scheme implementations (Chez scheme), the output is colored as expected.

**Comment by feeley** [comment]
This is due to the way Gambit handles console I/O to support its builtin "readline" feature and portable control of the terminal.  When ANSI escape codes are sent to the console they are decoded and put as "commands" into an output buffer.  Then, when the output buffer is flushed these commands are converted to the escapes sequences for the specific terminal that is used (using termcap or terminfo).  So there's a translation taking place.  This only works for the ANSI escape codes that are implemented in `lib/os_tty.c`... here is a list :

**Comment by c0nn3r** [comment]
Ah, I see. Thanks for the quick response!

**Comment by feeley** [comment]
To achieve what you want it is possible to change the tty's mode (in the Gambit runtime system) so that escape sequences will pass through uninterpreted (the "raw output" mode).  This can be done with the `(tty-mode-set! port input-allow-special input-echo input-raw output-raw)` procedure :

```
(define (display-raw str . port-opt)
  (let ((port (if (pair? port-opt) (car port-opt) (current-output-port))))
    (cond-expand (gambit (if (tty? port) (tty-mode-set! port #f #f #f #t)))
                 (else #f))
    (display str port)
    (cond-expand (gambit (if (tty? port) (tty-mode-set! port #f #f #f #f)))
                 (else #f))))

(display-raw "\033[38;2;255;0;0m")
(display "hello ")
(display-raw "\033[38;2;0;255;0m")
(display "world!\n")
(display-raw "\033[38;2;0;0;0m")
```

**Comment by c0nn3r** [comment]
Thank you, this was very helpful.
