### ISSUE TITLE
flat namespace linking on Darwin.

### ISSUE THREAD

**Issue by iains** [gambit/gambit#685]
Linking with flat namespace on Darwin will cause the linker to insert lazy binding for all external symbols (since with fact namespace every symbol is potentially interposable).

What problem is being solved with the current build using flat_namespace and "undefined suppress"?

(incidentally, the extra lazy binding stubs introduced by this happened to trigger the bug seen with GCC10.3, which is still a bug, of course).

**Comment by gambiteer** [comment]
Good question.

**Comment by feeley** [comment]
It used to be the case that the linker options `-flat_namespace -undefined suppress` were needed to create a shared object that could be loaded by `NSLinkModule` (the Darwin equivalent of `dlopen`).  Something related to the entry point not being found.  But this was probably 20 years ago so my memory may be failing me.  In a local branch I have disabled the use of these options and things seem to be working exactly the same, so I suspect Darwin has evolved and no longer needs that "hack".  Given that these linker options appear to be no longer needed and at the same time they are causing miscompilation by gcc 10.3, I will comment them out in the configure script so that they can easily be reactivated if we discover we forgot a situation where they are needed.

**Comment by iains** [comment]
JFTR - I think it *should* be unnecessary on any macOS version realistically supported by GCC today (i.e. 10.5+ [10.4 is feasible, but needs some TLC]).

There are other, more modern, solutions - such as using -Wl,-undefined,dynamic_lookup + rdynamic. 

However, if that can be avoided too it would be good because the Arm64 platform inherits extra restrictions from iOS (and I think dynamic lookup might not be available there).

IFF you need to reenable -flat_namespace we should discuss options ;) ... I don't think it can work 100% properly unless you disable inlining for any function that might need to be interposed (and that's independent of the bug).  This is because (including clang) if we have

int foo(int) {...}

int bar(int) {.. foo(x) ...}

AFAICT, at higher optimisations (which depends on clang c.f. GCC) foo will still be inlined into bar - which means any interposition of foo() would be 'partial'.

marking that function as __attribute__((__noinline__)) or switching inlining off for the library would solve that (as would also be the case if foo was a weak definition).

I guess this is intentional - since flat namespace is not really a common scheme for macOS and losing inlining would be a bad performance hit.

**Comment by feeley** [comment]
The fix is 920c16b81151a88151a17f274b816c5297f92ee8.
