### ISSUE TITLE
stamp.h keeps changing from git version

### ISSUE THREAD

**Issue by lassik** [gambit/gambit#690]
`include/stamp.h` is tracked in git, but keeps changing with each build. `git status` notices the change; it's unclear when (if ever) we should commit a new version of `stamp.h`.

Could we find some way to either add `stamp.h` to `.gitignore` (so git doesn't track changes to it) or change the build so it doesn't modify `stamp.h`?

**Comment by feeley** [comment]
It isn't clear what should be done with `stamp.h`.  It is meant to give a precise version information that will appear in `(system-stamp)` and `(system-version-string)`, which are also output by `gsi -v`.  When a release of Gambit is made the file `include/stamp.h` is modified to reflect the release version.  The file is also updated when a new git commit is made (so that it is clear that the Gambit being used is not an official release).  Ideally the new `include/stamp.h` file should be part of the committed files, but it can't because we don't yet know the git hash that will be created for that commit.  Another constraint is that `git` must not be required to build Gambit (i.e. the makefiles must work whether `git` is installed or not).

**Comment by lassik** [comment]
I suggest having separate `stamp-release.h` and `stamp-build.h` files (names up for debate).

* The release file tracks the latest release on which the current build is based. It's committed to version control and changed manually for each release.
* The build file is listed in `.gitignore`. It's auto-generated for each build.

**Comment by lassik** [comment]
We've had this problem with other implementations; the official-release check is extremely hard to do programmatically. So hard that it's probably best to label all builds as unofficial, unless an official flag is explicitly passed by a human.

**Comment by feeley** [comment]
OK that sounds good.  So we need to `git mv include/stamp.h include/stamp-release.h` and modify `include/makefile.in` so that when building Gambit the makefile creates `include/stamp.h` in a way that depends on the availability of `git` (and also doesn't touch the file if nothing changed, to avoid recompiling files needlessly).  The `stamp.h` file should just `#include "stamp-release.h"` if `git` is not available (the actual test is to check if the `.git` directory exists at the root because if it is there we can assume `git` is available).

Can you take care of this?

**Comment by lassik** [comment]
I can try.

What's the full set of information that is needed for each build?

* Gambit release on which it is based
* Release date?
* Is this an official build of that release or not? (manual flag)
* Build date and time (Y-M-D H:M:S)
* Git commit on which the build is based (if available)

**Comment by feeley** [comment]
I think the current `git describe --tag --always` is sufficient (in addition to the current time of the current commit).  For `stamp-release.h` it should contain the time of the release.

**Comment by lassik** [comment]
So the new `stamp.h` would be like this:

```C
#include "stamp-release.h"

#define ___STAMP_BUILD_GIT_DESCRIBE "v4.9.3-1396-g154a9ca0"
```

with the string value retrieved in from git at build time.

**Comment by feeley** [comment]
Actually I would instead generate a `stamp.h` containing only:

~~~
#define ___STAMP_VERSION_BUILD "v4.9.3-1396-g154a9ca0"
~~~

And let `_kernel.scm` do the `#include "stamp-release.h` in addition to `#include "stamp.h"`.  Then `_kernel.scm` can test `#ifdef ___STAMP_VERSION_BUILD` to use that instead of `___STAMP_VERSION`.  That way an empty file would work for `stamp.h` to easily build Gambit with just a `echo > include/stamp.h` on those systems that have very little build tools (such as the scripts in `misc` such as `misc/vstudio.bat`).

**Comment by lassik** [comment]
Yes, that's a better way to do it.

**Comment by lassik** [comment]
However, you should still somehow differentiate official release builds from unofficial and/or pre-release builds. The build should fall back to unofficial status in case of ambiguity or neglect.

**Comment by feeley** [comment]
This differentiation will happen naturally if the programmer building Gambit has done a `git` commit of their changes to the sources and uses the approved build steps.  I don't think we should be concerned of the case where the programmer doesn't do this.

It is more concerning that the bootstrap process was not performed correctly. I have seen this case very often. It seems to happen when the build is interrupted for example due to a C compiler crash or lack of resources (disk full, swap space full) or ctrl-C, and then the build is tried again.  I have seen cases where the Gambit version reported by `gsi -v` does not reflect the state of the post-bootstrap source code.

Moreover, the actual behaviour of Gambit depends on more than the source code that was compiled. The `configure` script auto-detects features of the operating system and enables Gambit runtime library features based on this.  If an auto-detection went wrong (a system header file or library wasn't found for any number of reasons) then it is possible the runtime system will behave differently by using a fallback (which in the worst case is a `not-implemented` exception at run time).  Maybe the symbols defined by the configure script should also be added to the information reported by `gsi -v`.  Currently, only the configure script command line arguments are reported.

**Comment by lassik** [comment]
People mostly install release versions of software from package managers nowadays. I would recommend the following:

* Indicating a build as the official release version needs to be done by setting an explicit official flag. Work with distributors to make sure they use the correct build procedure and set this flag. Maybe have some kind of test that verifies it?
* Self-built versions from git use `git describe` or similar to get the info.
* Self-built versions without git (e.g. from Gambit's official source release without using a package manager) get some kind of "self-built" indication.

**Comment by lassik** [comment]
For example, [here is the makefile used to build Gambit from FreeBSD ports](https://svnweb.freebsd.org/ports/head/lang/gambit-c/Makefile?revision=543589&view=markup). It would be easy to add some kind of official flag there.

**Comment by lassik** [comment]
In fact, the following could be adequate:

* `v4.9.3-git-g7b24d075`
* `v4.9.3-self-built`
* `v4.9.3-debian`
* `v4.9.3-freebsd`
* `v4.9.3-openbsd`

If someone sends in a bug report and the version says `v4.9.3-debian` you know that installed the Debian APT package.

**Comment by feeley** [comment]
Any reason to keep this open?

**Comment by lassik** [comment]
The `stamp.h` vs `stamp-release.h` issue has been solved, but the discussion on what items of version information to have is not settled. Perhaps it can be continued elsewhere.

**Comment by lassik** [comment]
Closing, since we're trying to solve the version info via SRFI 176.

**Comment by lassik** [comment]
PR #705
