### ISSUE TITLE
define-structure combined with c-define results in segmentation fault

### ISSUE THREAD

**Issue by wolneykien** [gambit/gambit#815]
If compiled with `gsc -exe test.scm` and run, the following example causes segmentation fault:

```
(define-structure test a b c)

;(define (make-test a b c)
;  (list a b c))

(c-define (make-test-wrapper a b c)
	  (int int int) scheme-object "make_test" ""
  (make-test a b c))

(define c-test
  (c-lambda () scheme-object
#<<c-lambda-end
  ___result = make_test (1, 2, 3);
c-lambda-end
  ))

(display (c-test))
(newline)
```

However, it runs OK if `make-test` declared normally (see the commented lines). Gambit v4.9.4.

**Comment by thchha** [comment]
`(display (c-test))` invokes a C-procedure without any arguments which shall return a `scheme-object`.
`c-test` declares an interface to a c-body which invokes ` SCMOBJ make_test(int a, int b, int c)`.
`(make-test-wrapper` is aliased as `make_test` on the C-side; Within its body it invokes the scheme procedure `(make-test`. 
If you uncomment `(make-test`, within the body of `make-test-wrapper` `make-test` is undefined and segfaults.

You are invoking a undefined procedure within the body of your scheme-procedure which shall be accessible from the C-side.

Maybe you omitted some things from your listing for readability.
Otherwise let us know if this already resolves your issue.

> Note that I'm a rookie and may be corrected :-) !

**Comment by feeley** [comment]
Thanks for reporting this bug. It was not related to `define-structure` but rather the case where Scheme calls C that calls Scheme that modifies `___ps->temp1` (a temporary used to return the error code). That temporary was set to "no error" too early and was being replaced by a value that made it look like there was an error in the Scheme call. The fix was to change the location where the "no error" code is put in the temporary (only 2 lines to change but it took a few hours to understand the cause of the problem).
