### ISSUE TITLE
make check fails on debugging support

### ISSUE THREAD

**Issue by jdf-id-au** [gambit/gambit#849]
I'm trying to compile so that I can use [`geiser-gambit`](https://gitlab.com/emacs-geiser/gambit).

On a M2 MacBook Air, macOS Ventura 13.4.1(c) this worked:
`./configure --enable-march=native --enable-dynamic-clib --enable-single-host --enable-debug --enable-rtlib-debug-source CC=/opt/homebrew/Cellar/gcc/13.1.0/bin/gcc-13 && make -j8`, albeit with many warnings of the form
```warning: (arm64)  could not find object file symbol for symbol ___subvdi3
warning: (arm64)  could not find object file symbol for symbol ___subvsi3
warning: (arm64)  could not find object file symbol for symbol ___mulvdi3
warning: (arm64)  could not find object file symbol for symbol ___mulvsi3
warning: (arm64)  could not find object file symbol for symbol ___negvdi2
warning: (arm64)  could not find object file symbol for symbol ___negvsi2
```

However, `make check` gives:
```
------------ TEST 1 (debugging support)
../gsi/gsi -:~~bin=../bin,~~lib=../lib,~~include=../include -f debug.scm > test1.out
diff test1.ok test1.out && rm -f test1.out
177,183c177,183
< #return(##cprc-let-values 5) : ($code rte)
< #return(##cprc-let-values 6) : ($code i inner-rte j2 ns patterns rte)
< #return(##cprc-let-values 7) : ($code args i inner-rte n ns patterns rte)
< #return(##cprc-let-values 8) : ($code arg i inner-rte n ns pattern patterns rte)
< #return(##cprc-let-values 9) : ($code arg args i inner-rte j k pattern patterns rte)
< #return(##cprc-let-values 10) : ($code args i inner-rte j patterns rte)
< #return(##cprc-let-values 11) : ($code args n ns patterns rte)
---
> #return(##cprc-let-values 5) : ($code args i inner-rte n ns patterns rte)
> #return(##cprc-let-values 6) : ($code arg i inner-rte n ns pattern patterns rte)
> #return(##cprc-let-values 7) : ($code rte)
> #return(##cprc-let-values 8) : ($code arg args i inner-rte j k pattern patterns rte)
> #return(##cprc-let-values 9) : ($code args i inner-rte j patterns rte)
> #return(##cprc-let-values 10) : ($code args n ns patterns rte)
> #return(##cprc-let-values 11) : ($code i inner-rte j2 ns patterns rte)
387c387,388
< #return(##cprc-guard 8) : ($code rte)
---
> #procedure(##cprc-guard 8)
> #return(##cprc-guard 9) : ($code rte)
make[1]: *** [test1] Error 1
make: *** [check] Error 2
```

Am I doing something wrong?

**Comment by feeley** [comment]
Concerning the warnings, it seems to be a known bug with the Xcode linker (see https://github.com/iains/gcc-darwin-arm64/issues/14). I also use gcc-13 on Apple M2 on a daily basis and get the same warnings, but the final program runs fine.

Concerning the `make check` failing, it is due to the use of the configure option `--enable-rtlib-debug-source`. This option adds debugging information to the whole runtime library including the interpreter. Apparently this causes the ordering of some return points to change, and `test1` thinks there is a problem because the ordering does not match the usual one (when build without `--enable-rtlib-debug-source`).

So you can either ignore this failure and instead do a `make ut` to run the unit-tests to check that they all pass. You could also configure Gambit without the `--enable-rtlib-debug-source` (an option that is only relevant if you intend to debug Gambit's runtime library).

I'll keep this issue open because the `test1` is overly constraining and it should be improved.

**Comment by gambiteer** [comment]
Marc:  Is this the same issue that caused this patch to "fail"?
https://github.com/gambit/gambit/issues/659
Here tests fail with the patch, but are these new test results valid, even if they don't match the expected results?

**Comment by feeley** [comment]
This issue is unrelated to #659. The `test1` failure reported above appears to be the correct return points, just not in the same order. The ordering is not important, but it is difficult to write down a test that ignores the ordering. Out of simplicity `test1` does a `diff` which works for the common case of not using `--enable-rtlib-debug-source`.
