### ISSUE TITLE
SRFI/42: duplicate pattern variable

### ISSUE THREAD

**Issue by wolneykien** [gambit/gambit#864]
Hi! When building v4.9.5 I get the following error:

```
make[5]: Entering directory '/usr/src/RPM/BUILD/gambit-4.9.5/lib/srfi/42'
>>>> building module srfi/42 for C
*** ERROR IN _define-library/define-library-expand#parse-define-library -- duplicate pattern variable
>>>> building module srfi/42 for js
*** ERROR IN _define-library/define-library-expand#parse-define-library -- duplicate pattern variable
make[5]: *** [../../module-common.mk:199: modules-pre] Error 70
make[5]: Leaving directory '/usr/src/RPM/BUILD/gambit-4.9.5/lib/srfi/42'
```

Even if the error happens due to some misconfiguration in the build setup, it would be nice to know which variable the error concerns. ;-)

**Comment by wolneykien** [comment]
I've made a couple of modifications which help me to debug the problem: #866 #867

**Comment by feeley** [comment]
The fundamental question is why your setup makes Gambit behave differently than it does here, where SRFI 42 build fine.

I have the impression your Gambit is under the influence of a stray binding of the GAMBOPT environment variable which changes the behavior of the runtime system (perhaps misinterpreting some of the symbols in SRFI 42 as keywords).

On my machine I get this behavior:

```
$ make -C lib/srfi/42 modules
>>>> building module srfi/42 for C
>>>> building module srfi/42 for js
$ gsc/gsc -v
v4.9.5-83-g7d462916 20231113214012 arm-apple-darwin23.0.0 "./configure '--enable-single-host' 'CC=gcc-13'"
$ gsc/gsc -e '(for-each (lambda (x) (pp (list x (symbol? x) (keyword? x)))) (quote (:do let foo: :)))'
(:do #t #f)
(let #t #f)
(foo: #f #t)
(: #t #f)
```

**Comment by wolneykien** [comment]
The ordinary (i.e. I maintain the package for a while) compilation options on x86_64 were:

```
./configure --build=x86_64-alt-linux --host=x86_64-alt-linux --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/lib --localstatedir=/var/lib --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-dependency-tracking --disable-silent-rules --without-included-gettext --enable-single-host --enable-shared --disable-absolute-shared-libs --docdir=/usr/share/doc/gambit-4.9.5
```

Today I've tried to add `--enable-dynamic-clib` and also to use `-O1` optimization (as was mentioned in `configure` warnings) and that seems to fix the problem.

**Comment by feeley** [comment]
I'm interested in understanding why you encountered these problems in the first place. I suspect it is because you are using `--enable-shared` and when `gsc` executes it incorrectly picks up the shared library of an old version of Gambit. Is there an easy way for you to trace the operations of the dynamic loader to see which shared libraries are being loaded? I suggest `strace` but there must be a more direct way.

So could you try again to build Gambit the way that reproduces the problem, and try tracing the dynamic loader to see where things are being loaded from?

If my theory is correct, then some changes to the makefiles should be done to ensure this doesn't happen again.

**Comment by wolneykien** [comment]
> when gsc executes it incorrectly picks up the shared library of an old version of Gambit

Sounds very improbable as the whole build process is performed in isolated environment built from scratch and Gambit is simply not installed there. However, I'll trace it down using `strace`. :-)

**Comment by feeley** [comment]
> Today I've tried to add `--enable-dynamic-clib` and also to use `-O1` optimization (as was mentioned in `configure` warnings) and that seems to fix the problem.

Could you try these changes independently to determine which one is the "solution"? If it is `--enable-dynamic-clib` it would be a problem with Gambit. If it is `-O1` it would be a bug with the C compiler. Do you have the specs of the C compiler?

**Comment by wolneykien** [comment]
> Could you try these changes independently to determine which one is the "solution"? If it is `--enable-dynamic-clib` it would be a problem with Gambit. If it is `-O1` it would be a bug with the C compiler. Do you have the specs of the C compiler?

Good news for you, Marc! (Or not? :-) ) It's probably the C compiler. However, it's GCC v13.2.1, so it might be serious.

I attach the `config.log` files which (by `env >>config.log`) were appended with shell environment (mainly, for `CFLAGS` and the like).

[config.unsuccessful.log](https://github.com/gambit/gambit/files/13530928/config.unsuccessful.log)
[config.O1.log](https://github.com/gambit/gambit/files/13530931/config.O1.log)

**Comment by feeley** [comment]
I'll look into it. I don't quite understand why `-O2` is making its way to the C compiler. Is the your default C optimization level?

**Comment by wolneykien** [comment]
Yes, `O2` is the default and it's easy to _append_ `O1`, but it's not so easy to replace the whole default options.

**Comment by feeley** [comment]
I've been struggling to reproduce the issue on a local machine (x86-64 with debian buster). The gcc compiler version is probably important if this is a C compiler bug. You seem to be using gcc 13.2.1 which I don't have.

I tried building gcc 13.2.1 from source and that failed with linking issues. I then installed nix and am using gcc 13.2.0 which is the closest to your setup that I can get.

I'm using the following script to build Gambit with the same compiler flags you seem to be using :

```
#!/bin/sh                                                                       

export CC="gcc"
export CFLAGS="-pipe -frecord-gcc-switches -Wall -g -O2 -flto=auto"

rm -rf boot gsc-boot
make clean
./configure --enable-single-host
make core
make modules
make check
```

This unfortunately failed with C linking issues, so I have tried to trim down the options in the `CFLAGS` settings in the hope of finding a combination where the `make core` is successful, but the `make modules` reproduces the issue. It seems that it is sufficient to have `CFLAGS="-O2"` for this.

I then tried the previous version of gcc available on nix (12.3.0) with `CFLAGS="-O2"` and both `make core` and `make modules` are successful.

So there was a breaking change between gcc 12.3.0 and gcc 13.2.0 when using `CFLAGS="-O2"`. Either this is caused by an optimization bug in gcc 13.2.0, or it is a latent "undefined behavior" issue in the C code generated by Gambit. I have the same version of gcc on a different architecture (gcc 13.2.0 on an Apple M2) and it does not exhibit the issue. This leaves us with this matrix:

```
gcc 13.2.0 aarch64   no issue
gcc 13.2.0 x86-64    ***issue present***
gcc 12.3.0 x86-64    no issue
```

This leaves me to believe there's a bug in the gcc 13.2.0 x86 code generator/optimizer.

Given that `-O2` should not he used anyway to compile Gambit (it can lead to slower code), the proper course of action here is to find a way to remove that from the C compiler flags.

**Comment by gambiteer** [comment]
I don't know what is meant by version 13.2.1 of `gcc`.  The latest version at `gcc.gnu.org` and `ftp.gnu.org` is 13.2.

**Comment by gambiteer** [comment]
I've built 13.2 and will investigate, but it's different to the kinds of things I usually bring to them.

**Comment by feeley** [comment]
I can try to narrow it down. What do you need?

**Comment by gambiteer** [comment]
Well, I would try to save and examine all intermediate commands (like the call to `cc1` and the linker) and save all intermediate files to try to see how and why a change to the optimization level could trigger this problem.  But it seems like a pretty high-level problem (in the Scheme expander).  It's not clear to me what file is being miscompiled.
