### ISSUE TITLE
Compilation Bug

### ISSUE THREAD

**Issue by dukester** [gambit/gambit#879]
> In file included from _num.c:1623:
> _num.c: In function ‘___H___num’:
> ../include/gambit.h:5225:1: internal compiler error: Segmentation fault
>  5225 | }
>       | ^
> ../include/gambit.h:2329:19: note: in definition of macro ‘___SM’
>  2329 | #define ___SM(s,m)s
>       |                   ^
> ../include/gambit.h:5186:28: note: in expansion of macro ‘___END_COD’
>  5186 | #define ___END_M_COD ___SM(___END_COD,___NOTHING)
>       |                            ^~~~~~~~~~
> _num.c:107179:1: note: in expansion of macro ‘___END_M_COD’
> 107179 | ___END_M_COD
>        | ^~~~~~~~~~~~
> 0x7f48e6d25d5f ???
>         ./signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
> 0x7f48e6d10d09 __libc_start_main
>         ../csu/libc-start.c:308
> Please submit a full bug report,
> with preprocessed source if appropriate.
> Please include the complete backtrace with any bug report.
> See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
> make[1]: *** [makefile:296: _num.o] Error 1
> make[1]: Leaving directory '/home/dnormandin/git/gambit/lib'
> make: *** [makefile:544: core-recursive] Error 1

Noob to Gambit / Scheme / and reporting bugs. Is there anything else on my Linux box that would help in dealing with the above issue? TIA ...

**Comment by gambiteer** [comment]
I notice you're using an older version of `gcc`:
```
 See file:///usr/share/doc/gcc-10/README.Bugs for instructions.
```
Is there a way for you to use a more modern `gcc`?

**Comment by dukester** [comment]
> gcc --version      
> gcc (Debian 10.2.1-6) 10.2.1 20210110
> 
Is that too old of a version? It's the latest on antiX Linux Debian buster repo!

**Comment by gambiteer** [comment]
Well, you're getting a segmentation fault inside of `gcc` when it tries to compile `_num.c`.
It's generally difficult to diagnose such things, I've done it a number of times with `gcc` trying to compile Gambit-generated code, but it isn't easy and I was not always successful.
Gcc 10 is no longer supported (see https://gcc.gnu.org/gcc-10/) so even if the problem was found, it wouldn't be fixed.
So I don't see how to proceed with this report.
If you know how to build and install gcc yourself you can build a later version.

**Comment by dukester** [comment]
> If you know how to build and install gcc yourself you can build a later version.
Thx - I'll have to give it a shot at least!

**Comment by feeley** [comment]
@dukester My guess is that the gcc bug is happening because of either too high of a C optimization level, or using the `--enable-single-host` configuration flag. Try configuring Gambit with `./configure CC=gcc-10` and see if that works. On my machine I have used `gcc-9` with no problem and `gcc-13` with no problem.

**Comment by gambiteer** [comment]
What Marc says ;-).

More specifically, please give your `configure` command with all the options and I'll look at it.

**Comment by feeley** [comment]
Closing this as it is stale, with no possible solution (the bug is in gcc).
