### ISSUE TITLE
Incorrect constant folding of eq?

### ISSUE THREAD

**Issue by gambiteer** [gambit/gambit#882]
This test file:
```
heine:~/programs/gambit/gambit-lucier> cat bignum-test.scm
(define a 1111111111111111111111111111111111111111)
(define b 1111111111111111111111111111111111111111)

(pretty-print (eq? a b))

(define c #t)
(define d #t)

(let ((a 1111111111111111111111111111111111111111)
      (b 1111111111111111111111111111111111111111))
  (pretty-print (eq? a b))
  (set! c a)
  (set! d b))

(pretty-print (eq? c d))
```
compiled with:
```
heine:~/programs/gambit/gambit-lucier> gsc -expansion bignum-test
Expansion:

(define a 1111111111111111111111111111111111111111)

(define b 1111111111111111111111111111111111111111)

(pretty-print
 (let ((temp.3 b) (temp.2 a))
   (if ('#<procedure #2 ##eq?> eq? '#<procedure #3 eq?>)
       ('#<procedure #2 ##eq?> temp.2 temp.3)
       (eq? temp.2 temp.3))))

(define c #t)

(define d #t)

(begin
  (pretty-print
   (if ('#<procedure #2 ##eq?> eq? '#<procedure #3 eq?>)
       #f   ;; <<<<<<<<<<<<<<<<<<<<<<<<<< incorrectly constant folded to #f
       (eq? 1111111111111111111111111111111111111111
            1111111111111111111111111111111111111111)))
  (set! c 1111111111111111111111111111111111111111)
  (set! d 1111111111111111111111111111111111111111))

(pretty-print
 (let ((temp.7 d) (temp.6 c))
   (if ('#<procedure #2 ##eq?> eq? '#<procedure #3 eq?>)
       ('#<procedure #2 ##eq?> temp.6 temp.7)
       (eq? temp.6 temp.7))))

```
and runs as:
```
heine:~/programs/gambit/gambit-lucier> gsi bignum-test
#t
#f
#t
```
I presume that the constant-folded result occurs because `a` and `b` are bignums.

**Comment by feeley** [comment]
That's an interesting issue! It is due to how literals are handled by the compiler. When the program is read, the parser constructs distinct objects for each 111...111 literal, i.e. they are not `eq?`. The front-end uses these distinct objects when it does constant folding and other optimizations. When the back-end generates the target C code, it accumulates the literal objects that are numbers in a table so that `eqv?` numbers are made unique. Doing this in the back-end is useful to catch multiple numerical literals of equal value (these literals can be created at macro expansion time, or by constant folding).

Note that it is correct (in the sense of RnRS) to do this. For example the R7RS says this about `eq?`:

On symbols, booleans, the empty list, pairs, and records, and also on non-empty strings, vectors, and bytevectors, `eq?` and `eqv?` are guaranteed to have the same behavior. On procedures, `eq?` must return true if the arguments’ location tags are equal. On numbers and characters, `eq?`’s behavior is implementation-dependent, but it will always return either true or false.

It is not clear what it would mean to "fix" this. What should the following print?

```
(define-macro (foo x)
  (let* ((n (expt 2 100))
         (test (eq? n x)))
    `'(,n ,x ,test)))

(define lst (foo 1267650600228229401496703205376))

(pretty-print (cons (eq? (car lst) (cadr lst)) lst))

;; v4.95 prints: (#t 1267650600228229401496703205376 1267650600228229401496703205376 #f)
;; in other words the numbers were considered to be
;; not eq? at macro-expansion time, but are eq? at execution time
```

**Comment by gambiteer** [comment]
I was aware that the definition of `eq?` allowed the behavior (I hit something similar with floating-point numbers a few years ago).  It seemed more like a quality of implementation issue.

Maybe `eq?` is such a cheap primitive that it shouldn't be constant folded.

**Comment by feeley** [comment]
Constant folding `eq?` is useful to enable/disable code based on the binding of a variable:

```
(declare (block))
(define mode 'debug)
(define (foo)
  (if (eq? mode 'debug) <lots-of-code>)
  ...)
```
So it is not simply a question of how fast `eq?` is at execution time.

Perhaps the result of `(eq? x y)` should be viewed differently: if `#t` then `x` and `y` are definitely the same object and if `#f` we know nothing about their identity.
