### ISSUE TITLE
Compiling a program using R7RS libraries

### ISSUE THREAD

**Issue by lassik** [gambit/gambit#933]
How do we use `gsc -exe` with R7RS libraries in the latest Gambit release? For example,

File `main.scm`:

```Scheme
(import (scheme base)
        (scheme write)
        (foo bar))

(write "HERE")
(newline)
(hello)
(write "HERE1")
(newline)
```

File `snow/foo/bar.sld`:

```Scheme
(define-library
  (foo bar)
  (import (scheme base)
          (scheme write))
  (export hello)
  (begin
    (include "bar/lib.scm")))
```

File `snow/foo/bar/lib.scm`:

```Scheme
(define hello
  (lambda ()
    (display "Hello")
    (newline)))
```

Trying to compile and run it:

```
$ gsc -exe snow/ main.scm; echo $?
0
$ ./main; echo $?
70
```

Precompiling the library with `gsc snow/foo/bar.sld` does not help.

**Comment by lassik** [comment]
cc @Retropikzel

**Comment by feeley** [comment]
What is missing is the `-nopreload` flag, which is explained in the documentation:

```
To create an executable program from a set of non-legacy modules
it is important to use the @code{-nopreload} linking option when linking so
that the modules will be initialized in an order that is consistent
with the module dependencies.  If the default @code{-preload} linking option
is used some modules may be initialized out of order, leading to incorrect
execution.
```

So this is the proper way to build and execute `main.scm`:

```
$ gsc -exe snow/ -nopreload main.scm; echo $?
0
$ ./main -:search=snow; echo $?
"HERE"
Hello
"HERE1"
0
$ ./main; echo $?
*** ERROR IN ##collect-modules -- Module not found
(##get-module 'foo/bar)
70
```

Note that this will dynamically load the library `(foo bar)`, which is why the directory `snow` is added to the module search order. It also means that the library `(foo bar)` will be interpreted, because it was never compiled.

Compiling the module `(foo bar)` can be achieved with:

```
$ gsc -:=.. snow/ foo/bar; echo $?
0
$ ls snow/foo
bar   bar.sld   bar@gambit409005@C
$ ./main -:search=snow; echo $?
"HERE"
Hello
"HERE1"
0
$ ./main; echo $?
*** ERROR IN ##collect-modules -- Module not found
(##get-module 'foo/bar)
70
```

If you want to create a self contained executable `main` there are various options. Here is one:

```
$ cd snow; gsc -c -o ../bar.c . foo/bar; cd ..   # create bar.c from snow/foo/bar.sld
$ gsc -exe -nopreload bar.c snow/ main.scm
$ ./main
"HERE"
Hello
"HERE1"
```

This is known to be user unfriendly. I am working on a better linker design (see #887).
